[package]
name = "emojisum"
version = "0.0.1"
authors = ["hello@organism.ai"]
description = "Emoji based cheksums"
license = "Apache-2.0"
repository = "https://github.com/stichtingorganism/emojisum"

[dependencies]
blake2-rfc = "0.2"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"