
// THIS FILE IS GENERATED. DO NOT EDIT.

package emoji

func init() {
  mapGen = VersionedMap{
	  Description: "This ordered list of emojiwords is the conventional order for the practice of conveying checksums with emoji. Each position provides the alternative for resolving the desired emoji.",
	  Version: "draft+2",
	  EmojiWords: []Words{
      Words{ ":+1:","U+1F44D",
      },
      Words{ ":8ball:","U+1F3B1",
      },
      Words{ ":airplane:","U+2708",
      },
      Words{ ":alien:","U+1F47D",
      },
      Words{ ":anchor:","U+2693",
      },
      Words{ ":angel:","U+1F607",
      },
      Words{ ":angry:","U+1F621",
      },
      Words{ ":ant:","U+1F41C",
      },
      Words{ ":apple:","U+1F34E",
      },
      Words{ ":art:","U+1F3A8",
      },
      Words{ ":baby:","U+1F476",
      },
      Words{ ":baby_bottle:","U+1F37C",
      },
      Words{ ":back:","U+1F519",
      },
      Words{ ":bamboo:","U+1F38D",
      },
      Words{ ":banana:","U+1F34C",
      },
      Words{ ":barber:","U+1F488",
      },
      Words{ ":bathtub:","U+1F6C1",
      },
      Words{ ":beer:","U+1F37A",
      },
      Words{ ":bell:","U+1F514",
      },
      Words{ ":bicyclist:","U+1F6B4",
      },
      Words{ ":bird:","U+1F426",
      },
      Words{ ":birthday:","U+1F382",
      },
      Words{ ":blossom:","U+1F33C",
      },
      Words{ ":blue_car:","U+1F693",
      },
      Words{ ":boar:","U+1F417",
      },
      Words{ ":bomb:","U+1F4A3",
      },
      Words{ ":boom:","U+1F4A5",
      },
      Words{ ":bow:","U+1F3F9",
      },
      Words{ ":boy:","U+1F466",
      },
      Words{ ":broken_heart:","U+1F494",
      },
      Words{ ":bulb:","U+1F4A1",
      },
      Words{ ":bus:","U+1F68C",
      },
      Words{ ":cactus:",
      },
      Words{ ":calendar:",
      },
      Words{ ":camera:",
      },
      Words{ ":candy:",
      },
      Words{ ":cat:",
      },
      Words{ ":cherries:",
      },
      Words{ ":children_crossing:",
      },
      Words{ ":chocolate_bar:",
      },
      Words{ ":clap:",
      },
      Words{ ":cloud:",
      },
      Words{ ":clubs:",
      },
      Words{ ":cn:",
      },
      Words{ ":coffee:",
      },
      Words{ ":construction:",
      },
      Words{ ":cookie:",
      },
      Words{ ":copyright:",
      },
      Words{ ":corn:",
      },
      Words{ ":cow:",
      },
      Words{ ":crescent_moon:",
      },
      Words{ ":crown:",
      },
      Words{ ":cry:",
      },
      Words{ ":crystal_ball:",
      },
      Words{ ":curly_loop:",
      },
      Words{ ":dancers:",
      },
      Words{ ":dash:",
      },
      Words{ ":de:",
      },
      Words{ ":diamonds:",
      },
      Words{ ":dog:",
      },
      Words{ ":doughnut:",
      },
      Words{ ":dragon:",
      },
      Words{ ":dvd:",
      },
      Words{ ":ear:",
      },
      Words{ ":eggplant:",
      },
      Words{ ":elephant:",
      },
      Words{ ":end:",
      },
      Words{ ":envelope:",
      },
      Words{ ":es:",
      },
      Words{ ":eyes:",
      },
      Words{ ":facepunch:",
      },
      Words{ ":family:",
      },
      Words{ ":ferris_wheel:",
      },
      Words{ ":cold_sweat:","U+1F630",
      },
      Words{ ":fire:",
      },
      Words{ ":fireworks:",
      },
      Words{ ":floppy_disk:",
      },
      Words{ ":football:",
      },
      Words{ ":fork_and_knife:",
      },
      Words{ ":four_leaf_clover:",
      },
      Words{ ":fr:",
      },
      Words{ ":fries:",
      },
      Words{ ":frog:",
      },
      Words{ ":fu:",
      },
      Words{ ":full_moon:",
      },
      Words{ ":game_die:",
      },
      Words{ ":eu:",
      },
      Words{ ":gem:",
      },
      Words{ ":girl:",
      },
      Words{ ":goat:",
      },
      Words{ ":grimacing:",
      },
      Words{ ":grin:",
      },
      Words{ ":guardsman:",
      },
      Words{ ":guitar:",
      },
      Words{ ":gun:",
      },
      Words{ ":hamburger:",
      },
      Words{ ":hammer:",
      },
      Words{ ":hamster:",
      },
      Words{ ":hear_no_evil:",
      },
      Words{ ":heart:",
      },
      Words{ ":heart_eyes_cat:",
      },
      Words{ ":hearts:",
      },
      Words{ ":heavy_check_mark:",
      },
      Words{ ":moyai:",
      },
      Words{ ":izakaya_lantern:",
      },
      Words{ ":helicopter:",
      },
      Words{ ":hocho:",
      },
      Words{ ":honeybee:",
      },
      Words{ ":horse:",
      },
      Words{ ":horse_racing:",
      },
      Words{ ":hourglass:",
      },
      Words{ ":house:",
      },
      Words{ ":hurtrealbad:",
      },
      Words{ ":icecream:",
      },
      Words{ ":imp:",
      },
      Words{ ":it:",
      },
      Words{ ":jack_o_lantern:",
      },
      Words{ ":japanese_goblin:",
      },
      Words{ ":jp:",
      },
      Words{ ":key:",
      },
      Words{ ":kiss:",
      },
      Words{ ":kissing_cat:",
      },
      Words{ ":koala:",
      },
      Words{ ":kr:",
      },
      Words{ ":lemon:",
      },
      Words{ ":lipstick:",
      },
      Words{ ":lock:",
      },
      Words{ ":lollipop:",
      },
      Words{ ":man:",
      },
      Words{ ":maple_leaf:",
      },
      Words{ ":mask:",
      },
      Words{ ":metal:","U+1F918",
      },
      Words{ ":microscope:",
      },
      Words{ ":moneybag:",
      },
      Words{ ":monkey:",
      },
      Words{ ":mount_fuji:",
      },
      Words{ ":muscle:",
      },
      Words{ ":mushroom:",
      },
      Words{ ":musical_keyboard:",
      },
      Words{ ":musical_score:",
      },
      Words{ ":nail_care:",
      },
      Words{ ":new_moon:",
      },
      Words{ ":no_entry:",
      },
      Words{ ":nose:",
      },
      Words{ ":notes:",
      },
      Words{ ":nut_and_bolt:",
      },
      Words{ ":o:",
      },
      Words{ ":ocean:",
      },
      Words{ ":ok_hand:",
      },
      Words{ ":on:",
      },
      Words{ ":package:",
      },
      Words{ ":palm_tree:",
      },
      Words{ ":panda_face:",
      },
      Words{ ":paperclip:",
      },
      Words{ ":partly_sunny:",
      },
      Words{ ":passport_control:",
      },
      Words{ ":paw_prints:",
      },
      Words{ ":peach:",
      },
      Words{ ":penguin:",
      },
      Words{ ":phone:",
      },
      Words{ ":pig:",
      },
      Words{ ":pill:",
      },
      Words{ ":pineapple:",
      },
      Words{ ":pizza:",
      },
      Words{ ":point_left:",
      },
      Words{ ":point_right:",
      },
      Words{ ":poop:",
      },
      Words{ ":poultry_leg:",
      },
      Words{ ":pray:",
      },
      Words{ ":princess:",
      },
      Words{ ":purse:",
      },
      Words{ ":pushpin:",
      },
      Words{ ":rabbit:",
      },
      Words{ ":rainbow:",
      },
      Words{ ":raised_hand:",
      },
      Words{ ":recycle:",
      },
      Words{ ":red_car:",
      },
      Words{ ":registered:",
      },
      Words{ ":ribbon:",
      },
      Words{ ":rice:",
      },
      Words{ ":rocket:",
      },
      Words{ ":roller_coaster:",
      },
      Words{ ":rooster:",
      },
      Words{ ":ru:",
      },
      Words{ ":sailboat:",
      },
      Words{ ":santa:",
      },
      Words{ ":satellite:",
      },
      Words{ ":satisfied:",
      },
      Words{ ":saxophone:",
      },
      Words{ ":scissors:",
      },
      Words{ ":see_no_evil:",
      },
      Words{ ":sheep:",
      },
      Words{ ":shell:",
      },
      Words{ ":shoe:",
      },
      Words{ ":ski:",
      },
      Words{ ":skull:",
      },
      Words{ ":sleepy:",
      },
      Words{ ":smile:",
      },
      Words{ ":smiley_cat:",
      },
      Words{ ":smirk:",
      },
      Words{ ":smoking:",
      },
      Words{ ":snail:",
      },
      Words{ ":snake:",
      },
      Words{ ":snowflake:",
      },
      Words{ ":soccer:",
      },
      Words{ ":soon:",
      },
      Words{ ":space_invader:",
      },
      Words{ ":spades:",
      },
      Words{ ":speak_no_evil:",
      },
      Words{ ":star:",
      },
      Words{ ":stars:",
      },
      Words{ ":statue_of_liberty:",
      },
      Words{ ":steam_locomotive:",
      },
      Words{ ":sunflower:",
      },
      Words{ ":sunglasses:",
      },
      Words{ ":sunny:",
      },
      Words{ ":sunrise:",
      },
      Words{ ":surfer:",
      },
      Words{ ":swimmer:",
      },
      Words{ ":syringe:",
      },
      Words{ ":tada:",
      },
      Words{ ":tangerine:",
      },
      Words{ ":taxi:",
      },
      Words{ ":tennis:",
      },
      Words{ ":tent:",
      },
      Words{ ":thought_balloon:",
      },
      Words{ ":tm:",
      },
      Words{ ":toilet:",
      },
      Words{ ":tongue:",
      },
      Words{ ":tophat:",
      },
      Words{ ":tractor:",
      },
      Words{ ":trolleybus:",
      },
      Words{ ":trollface:",
      },
      Words{ ":trophy:",
      },
      Words{ ":trumpet:",
      },
      Words{ ":turtle:",
      },
      Words{ ":two_men_holding_hands:",
      },
      Words{ ":two_women_holding_hands:",
      },
      Words{ ":uk:",
      },
      Words{ ":umbrella:",
      },
      Words{ ":unlock:",
      },
      Words{ ":us:",
      },
      Words{ ":v:",
      },
      Words{ ":vhs:",
      },
      Words{ ":violin:",
      },
      Words{ ":warning:",
      },
      Words{ ":watermelon:",
      },
      Words{ ":wave:",
      },
      Words{ ":wavy_dash:",
      },
      Words{ ":wc:",
      },
      Words{ ":wheelchair:",
      },
      Words{ ":woman:",
      },
      Words{ ":x:",
      },
      Words{ ":yum:",
      },
      Words{ ":zap:",
      },
      Words{ ":zzz:",
      },
	  },
  }
}
