
// THIS FILE IS GENERATED. DO NOT EDIT.

package emoji

func init() {
  mapGen = VersionedMap{
	  Description: "This ordered list of emojiwords is the conventional order for the practice of conveying checksums with emoji. Each position provides the alternative for resolving the desired emoji.",
	  Version: "draft+3",
	  EmojiWords: []Words{
      Words{ ":+1:","U+1F44D",
      },
      Words{ ":8ball:","U+1F3B1",
      },
      Words{ ":airplane:","U+2708",
      },
      Words{ ":alien:","U+1F47D",
      },
      Words{ ":anchor:","U+2693",
      },
      Words{ ":angel:","U+1F607",
      },
      Words{ ":angry:","U+1F621",
      },
      Words{ ":ant:","U+1F41C",
      },
      Words{ ":apple:","U+1F34E",
      },
      Words{ ":art:","U+1F3A8",
      },
      Words{ ":baby:","U+1F476",
      },
      Words{ ":baby_bottle:","U+1F37C",
      },
      Words{ ":back:","U+1F519",
      },
      Words{ ":bamboo:","U+1F38D",
      },
      Words{ ":banana:","U+1F34C",
      },
      Words{ ":barber:","U+1F488",
      },
      Words{ ":bathtub:","U+1F6C1",
      },
      Words{ ":beer:","U+1F37A",
      },
      Words{ ":bell:","U+1F514",
      },
      Words{ ":bicyclist:","U+1F6B4",
      },
      Words{ ":bird:","U+1F426",
      },
      Words{ ":birthday:","U+1F382",
      },
      Words{ ":blossom:","U+1F33C",
      },
      Words{ ":blue_car:","U+1F693",
      },
      Words{ ":boar:","U+1F417",
      },
      Words{ ":bomb:","U+1F4A3",
      },
      Words{ ":boom:","U+1F4A5",
      },
      Words{ ":bow:","U+1F3F9",
      },
      Words{ ":boy:","U+1F466",
      },
      Words{ ":broken_heart:","U+1F494",
      },
      Words{ ":bulb:","U+1F4A1",
      },
      Words{ ":bus:","U+1F68C",
      },
      Words{ ":cactus:","U+1F335",
      },
      Words{ ":calendar:","U+1F4C5",
      },
      Words{ ":camera:","U+1F4F7",
      },
      Words{ ":candy:","U+1F36C",
      },
      Words{ ":cat:","U+1F431",
      },
      Words{ ":cherries:","U+1F352",
      },
      Words{ ":children_crossing:","U+1F6B8",
      },
      Words{ ":chocolate_bar:","U+1F36B",
      },
      Words{ ":clap:","U+1F44F",
      },
      Words{ ":cloud:","U+2601",
      },
      Words{ ":clubs:","U+2663",
      },
      Words{ ":cn:","U+1F1E8U+1F1F3",
      },
      Words{ ":coffee:","U+2615",
      },
      Words{ ":construction:","U+1F6A7",
      },
      Words{ ":cookie:","U+1F36A",
      },
      Words{ ":copyright:","U+00A9",
      },
      Words{ ":corn:","U+1F33D",
      },
      Words{ ":cow:","U+1F42E",
      },
      Words{ ":crescent_moon:","U+1F319",
      },
      Words{ ":crown:","U+1F451",
      },
      Words{ ":cry:","U+1F622",
      },
      Words{ ":crystal_ball:","U+1F52E",
      },
      Words{ ":curly_loop:","U+27B0",
      },
      Words{ ":dancers:","U+1F46F",
      },
      Words{ ":dash:","U+1F4A8",
      },
      Words{ ":de:","U+1F1E9U+1F1EA",
      },
      Words{ ":diamonds:","U+2666",
      },
      Words{ ":dog:","U+1F436",
      },
      Words{ ":doughnut:","U+1F369",
      },
      Words{ ":dragon:","U+1F409",
      },
      Words{ ":dvd:","U+1F4C0",
      },
      Words{ ":ear:","U+1F442",
      },
      Words{ ":eggplant:","U+1F346",
      },
      Words{ ":elephant:","U+1F418",
      },
      Words{ ":end:","U+1F51A",
      },
      Words{ ":envelope:","U+2709",
      },
      Words{ ":es:","U+1F1EAU+1F1F8",
      },
      Words{ ":eyes:","U+1F440",
      },
      Words{ ":facepunch:","U+1F44A",
      },
      Words{ ":family:","U+1F46A",
      },
      Words{ ":ferris_wheel:","U+1F3A1",
      },
      Words{ ":cold_sweat:","U+1F630",
      },
      Words{ ":fire:","U+1F525",
      },
      Words{ ":fireworks:","U+1F386",
      },
      Words{ ":floppy_disk:","U+1F4BE",
      },
      Words{ ":football:","U+1F3C8",
      },
      Words{ ":fork_and_knife:","U+1F374",
      },
      Words{ ":four_leaf_clover:","U+1F340",
      },
      Words{ ":fr:","U+1F1EBU+1F1F7",
      },
      Words{ ":fries:","U+1F35F",
      },
      Words{ ":peanuts:","U+1F95C",
      },
      Words{ ":fu:","U+1F595",
      },
      Words{ ":full_moon:","U+1F315",
      },
      Words{ ":game_die:","U+1F3B2",
      },
      Words{ ":eu:","U+1F1EAU+1F1FA",
      },
      Words{ ":gem:","U+1F48E",
      },
      Words{ ":girl:","U+1F467",
      },
      Words{ ":goat:","U+1F410",
      },
      Words{ ":grimacing:","U+1F62C",
      },
      Words{ ":grin:","U+1F600",
      },
      Words{ ":guardsman:","U+1F482",
      },
      Words{ ":guitar:","U+1F3B8",
      },
      Words{ ":gun:","U+1F52B",
      },
      Words{ ":hamburger:","U+1F354",
      },
      Words{ ":hammer:","U+1F528",
      },
      Words{ ":hamster:","U+1F439",
      },
      Words{ ":hear_no_evil:","U+1F649",
      },
      Words{ ":heart:","U+2764",
      },
      Words{ ":heart_eyes_cat:","U+1F63B",
      },
      Words{ ":heavy_heart_exclamation:","U+2763",
      },
      Words{ ":heavy_check_mark:","U+2714",
      },
      Words{ ":moyai:",":moai:","U+1F5FF",
      },
      Words{ ":izakaya_lantern:","U+1F3EE",
      },
      Words{ ":helicopter:","U+1F681",
      },
      Words{ ":hocho:","U+1F52A",
      },
      Words{ ":honeybee:","U+1F41D",
      },
      Words{ ":horse:","U+1F434",
      },
      Words{ ":horse_racing:","U+1F3C7",
      },
      Words{ ":hourglass:","U+231B",
      },
      Words{ ":house:","U+1F3E0",
      },
      Words{ ":female_detective:",":detective:","U+1F575","U+1F575U+FE0FU+200DU+2642U+FE0F","U+1F575U+FE0FU+200DU+2640U+FE0F",
      },
      Words{ ":icecream:","U+1F366",
      },
      Words{ ":imp:","U+1F608",
      },
      Words{ ":it:","U+1F1EEU+1F1F9",
      },
      Words{ ":jack_o_lantern:","U+1F383",
      },
      Words{ ":japanese_goblin:","U+1F47A",
      },
      Words{ ":jp:","U+1F1EFU+1F1F5",
      },
      Words{ ":key:","U+1F511",
      },
      Words{ ":kiss:","U+1F48B",
      },
      Words{ ":kissing_cat:","U+1F63D",
      },
      Words{ ":koala:","U+1F428",
      },
      Words{ ":kr:","U+1F1F0U+1F1F7",
      },
      Words{ ":lemon:","U+1F34B",
      },
      Words{ ":lipstick:","U+1F484",
      },
      Words{ ":lock:","U+1F512",
      },
      Words{ ":lollipop:","U+1F36D",
      },
      Words{ ":man:","U+1F468",
      },
      Words{ ":maple_leaf:","U+1F341",
      },
      Words{ ":mask:","U+1F637",
      },
      Words{ ":metal:","U+1F918",
      },
      Words{ ":microscope:","U+1F52C",
      },
      Words{ ":moneybag:","U+1F4B0",
      },
      Words{ ":monkey:","U+1F412",
      },
      Words{ ":mount_fuji:","U+1F5FB",
      },
      Words{ ":muscle:","U+1F4AA",
      },
      Words{ ":mushroom:","U+1F344",
      },
      Words{ ":musical_keyboard:","U+1F3B9",
      },
      Words{ ":musical_score:","U+1F3BC",
      },
      Words{ ":nail_care:","U+1F485",
      },
      Words{ ":new_moon:","U+1F311",
      },
      Words{ ":no_entry:","U+26D4",
      },
      Words{ ":nose:","U+1F443",
      },
      Words{ ":control_knobs:","U+1F39B",
      },
      Words{ ":nut_and_bolt:","U+1F529",
      },
      Words{ ":o:","U+2B55",
      },
      Words{ ":ocean:","U+1F30A",
      },
      Words{ ":ok_hand:","U+1F44C",
      },
      Words{ ":on:","U+1F51B",
      },
      Words{ ":package:","U+1F4E6",
      },
      Words{ ":palm_tree:","U+1F334",
      },
      Words{ ":panda_face:","U+1F43C",
      },
      Words{ ":paperclip:","U+1F4CE","U+1F587",
      },
      Words{ ":partly_sunny:","U+26C5","U+1F324","U+1F325",
      },
      Words{ ":passport_control:","U+1F6C2","U+1F6C3",
      },
      Words{ ":paw_prints:","U+1F43E",
      },
      Words{ ":peach:","U+1F351",
      },
      Words{ ":penguin:","U+1F427",
      },
      Words{ ":phone:","U+260E",
      },
      Words{ ":pig:","U+1F437",
      },
      Words{ ":pill:","U+1F48A",
      },
      Words{ ":pineapple:","U+1F34D",
      },
      Words{ ":pizza:","U+1F355",
      },
      Words{ ":point_left:","U+1F448",
      },
      Words{ ":point_right:","U+1F449",
      },
      Words{ ":poop:","U+1F4A9",
      },
      Words{ ":poultry_leg:","U+1F357",
      },
      Words{ ":pray:","U+1F64F",
      },
      Words{ ":princess:","U+1F478",
      },
      Words{ ":purse:","U+1F45B",
      },
      Words{ ":pushpin:","U+1F4CC","U+1F4CD",
      },
      Words{ ":rabbit:","U+1F430",
      },
      Words{ ":rainbow:","U+1F308",
      },
      Words{ ":raised_hand:","U+270B",
      },
      Words{ ":recycle:","U+267B",
      },
      Words{ ":red_car:","U+1F697",
      },
      Words{ ":registered:","U+00AE",
      },
      Words{ ":ribbon:","U+1F380",
      },
      Words{ ":rice:","U+1F35A",
      },
      Words{ ":rocket:","U+1F680",
      },
      Words{ ":roller_coaster:","U+1F3A2",
      },
      Words{ ":rooster:","U+1F413",
      },
      Words{ ":ru:","U+1F1F7U+1F1FA",
      },
      Words{ ":sailboat:","U+26F5",
      },
      Words{ ":santa:","U+1F385",
      },
      Words{ ":satellite:","U+1F6F0",
      },
      Words{ ":satisfied:","U+1F606",
      },
      Words{ ":saxophone:","U+1F3B7",
      },
      Words{ ":scissors:","U+2702",
      },
      Words{ ":see_no_evil:","U+1F648",
      },
      Words{ ":sheep:","U+1F411","U+1F40F",
      },
      Words{ ":shell:","U+1F41A",
      },
      Words{ ":shoe:","U+1F45E","U+1F45F",
      },
      Words{ ":ski:","U+1F3BF",
      },
      Words{ ":skull:","U+1F480",
      },
      Words{ ":sleepy:","U+1F62A",
      },
      Words{ ":smile:","U+1F604",
      },
      Words{ ":smiley_cat:","U+1F63A",
      },
      Words{ ":smirk:","U+1F60F",
      },
      Words{ ":smoking:","U+1F6AC",
      },
      Words{ ":snail:","U+1F40C",
      },
      Words{ ":snake:","U+1F40D",
      },
      Words{ ":snowflake:","U+FE0F","U+2744",
      },
      Words{ ":soccer:","U+26BD",
      },
      Words{ ":soon:","U+1F51C",
      },
      Words{ ":space_invader:","U+1F47E",
      },
      Words{ ":spades:","U+2660",
      },
      Words{ ":speak_no_evil:","U+1F64A",
      },
      Words{ ":star:","U+2B50","U+1F31F",
      },
      Words{ ":fountain:","U+26F2",
      },
      Words{ ":statue_of_liberty:","U+1F5FD",
      },
      Words{ ":steam_locomotive:","U+1F682",
      },
      Words{ ":sunflower:","U+1F33B",
      },
      Words{ ":sunglasses:","U+1F576",
      },
      Words{ ":sunny:","U+2600",
      },
      Words{ ":sunrise:","U+1F304","U+1F305",
      },
      Words{ ":surfer:","U+1F3C4","U+1F3C4U+200DU+2642U+FEOF","U+1F3C4U+200DU+2640U+FEOF",
      },
      Words{ ":swimmer:","U+1F3CA","U+1F3CAU+200DU+2640U+FE0F","U+1F3CAU+200DU+2642U+FE0F",
      },
      Words{ ":syringe:","U+1F489",
      },
      Words{ ":tada:","U+1F389","U+1F38A",
      },
      Words{ ":tangerine:","U+1F34A",
      },
      Words{ ":taxi:","U+1F695",
      },
      Words{ ":tennis:","U+1F3BE",
      },
      Words{ ":tent:","U+26FA",
      },
      Words{ ":thought_balloon:","U+1F4AD",
      },
      Words{ ":tm:","U+2122",
      },
      Words{ ":toilet:","U+1F6BD",
      },
      Words{ ":tongue:","U+1F445",
      },
      Words{ ":tophat:","U+1F3A9",
      },
      Words{ ":tractor:","U+1F69C",
      },
      Words{ ":trolleybus:","U+1F68E",
      },
      Words{ ":nauseated_face:","U+1F922",
      },
      Words{ ":trophy:","U+1F3C6",
      },
      Words{ ":trumpet:","U+1F3BA",
      },
      Words{ ":turtle:","U+1F422",
      },
      Words{ ":carousel_horse:","U+1F3A0",
      },
      Words{ ":two_women_holding_hands:",":two_men_holding_hands:",":couple:","U+1F46C","U+1F46D","U+1F46B",
      },
      Words{ ":uk:","U+1F1ECU+1F1E7",
      },
      Words{ ":umbrella:","U+2602","U+2614",
      },
      Words{ ":unlock:","U+1F513",
      },
      Words{ ":us:","U+1F1FAU+1F1F8",
      },
      Words{ ":v:","U+270C",
      },
      Words{ ":vhs:","U+1F4FC",
      },
      Words{ ":violin:","U+1F3BB",
      },
      Words{ ":warning:","U+26A0",
      },
      Words{ ":watermelon:","U+1F349",
      },
      Words{ ":wave:","U+1F44B",
      },
      Words{ ":wavy_dash:","U+3030",
      },
      Words{ ":wc:","U+1F6BE",
      },
      Words{ ":wheelchair:","U+267F",
      },
      Words{ ":woman:","U+1F469",
      },
      Words{ ":x:","U+2716","U+274C",
      },
      Words{ ":yum:","U+1F60B",
      },
      Words{ ":zap:","U+26A1",
      },
      Words{ ":zzz:","U+1F4A4",
      },
	  },
  }
}
