
// THIS FILE IS GENERATED. DO NOT EDIT.

package emoji

func init() {
  mapGen = VersionedMap{
	  Description: "This ordered list of emojiwords is the conventional order for the practice of conveying checksums with emoji. Each position provides the alternative for resolving the desired emoji.",
	  Version: "draft+2",
	  EmojiWords: []Words{
      Words{ ":+1:","U+1F44D",
      },
      Words{ ":8ball:","U+1F3B1",
      },
      Words{ ":airplane:","U+2708",
      },
      Words{ ":alien:","U+1F47D",
      },
      Words{ ":anchor:","U+2693",
      },
      Words{ ":angel:","U+1F607",
      },
      Words{ ":angry:","U+1F621",
      },
      Words{ ":ant:","U+1F41C",
      },
      Words{ ":apple:","U+1F34E",
      },
      Words{ ":art:","U+1F3A8",
      },
      Words{ ":baby:","U+1F476",
      },
      Words{ ":baby_bottle:","U+1F37C",
      },
      Words{ ":back:","U+1F519",
      },
      Words{ ":bamboo:","U+1F38D",
      },
      Words{ ":banana:","U+1F34C",
      },
      Words{ ":barber:","U+1F488",
      },
      Words{ ":bathtub:","U+1F6C1",
      },
      Words{ ":beer:","U+1F37A",
      },
      Words{ ":bell:","U+1F514",
      },
      Words{ ":bicyclist:","U+1F6B4",
      },
      Words{ ":bird:","U+1F426",
      },
      Words{ ":birthday:","U+1F382",
      },
      Words{ ":blossom:","U+1F33C",
      },
      Words{ ":blue_car:","U+1F693",
      },
      Words{ ":boar:","U+1F417",
      },
      Words{ ":bomb:","U+1F4A3",
      },
      Words{ ":boom:","U+1F4A5",
      },
      Words{ ":bow:","U+1F3F9",
      },
      Words{ ":boy:","U+1F466",
      },
      Words{ ":broken_heart:","U+1F494",
      },
      Words{ ":bulb:","U+1F4A1",
      },
      Words{ ":bus:","U+1F68C",
      },
      Words{ ":cactus:","U+1F335",
      },
      Words{ ":calendar:","U+1F4C5",
      },
      Words{ ":camera:","U+1F4F7",
      },
      Words{ ":candy:","U+1F36C",
      },
      Words{ ":cat:","U+1F431",
      },
      Words{ ":cherries:","U+1F352",
      },
      Words{ ":children_crossing:","U+1F6B8",
      },
      Words{ ":chocolate_bar:","U+1F36B",
      },
      Words{ ":clap:","U+1F44F",
      },
      Words{ ":cloud:","U+2601",
      },
      Words{ ":clubs:","U+2663",
      },
      Words{ ":cn:","U+1F1E8","U+1F1F3",
      },
      Words{ ":coffee:","U+2615",
      },
      Words{ ":construction:","U+1F6A7",
      },
      Words{ ":cookie:","U+1F36A",
      },
      Words{ ":copyright:","U+00A9",
      },
      Words{ ":corn:","U+1F33D",
      },
      Words{ ":cow:","U+1F42E",
      },
      Words{ ":crescent_moon:","U+1F319",
      },
      Words{ ":crown:","U+1F451",
      },
      Words{ ":cry:","U+1F622",
      },
      Words{ ":crystal_ball:","U+1F52E",
      },
      Words{ ":curly_loop:","U+27B0",
      },
      Words{ ":dancers:","U+1F46F",
      },
      Words{ ":dash:","U+1F4A8",
      },
      Words{ ":de:","U+1F1E9","U+1F1EA",
      },
      Words{ ":diamonds:","U+2666",
      },
      Words{ ":dog:","U+1F436",
      },
      Words{ ":doughnut:","U+1F369",
      },
      Words{ ":dragon:","U+1F409",
      },
      Words{ ":dvd:","U+1F4C0",
      },
      Words{ ":ear:","U+1F442",
      },
      Words{ ":eggplant:","U+1F346",
      },
      Words{ ":elephant:","U+1F418",
      },
      Words{ ":end:","U+1F51A",
      },
      Words{ ":envelope:","U+2709",
      },
      Words{ ":es:","U+1F1EA","U+1F1F8",
      },
      Words{ ":eyes:","U+1F440",
      },
      Words{ ":facepunch:","U+1F44A",
      },
      Words{ ":family:","U+1F46A",
      },
      Words{ ":ferris_wheel:","U+1F3A1",
      },
      Words{ ":cold_sweat:","U+1F630",
      },
      Words{ ":fire:","U+1F525",
      },
      Words{ ":fireworks:","U+1F386",
      },
      Words{ ":floppy_disk:","U+1F4BE",
      },
      Words{ ":football:","U+1F3C8",
      },
      Words{ ":fork_and_knife:","U+1F374",
      },
      Words{ ":four_leaf_clover:","U+1F340",
      },
      Words{ ":fr:","U+1F1EB","U+1F1F7",
      },
      Words{ ":fries:","U+1F35F",
      },
      Words{ ":frog:",
      },
      Words{ ":fu:","U+1F595",
      },
      Words{ ":full_moon:","U+1F315",
      },
      Words{ ":game_die:","U+1F3B2",
      },
      Words{ ":eu:","U+1F1EA","U+1F1FA",
      },
      Words{ ":gem:","U+1F48E",
      },
      Words{ ":girl:","U+1F467",
      },
      Words{ ":goat:","U+1F410",
      },
      Words{ ":grimacing:","U+1F62C",
      },
      Words{ ":grin:","U+1F600",
      },
      Words{ ":guardsman:","U+1F482",
      },
      Words{ ":guitar:","U+1F3B8",
      },
      Words{ ":gun:","U+1F52B",
      },
      Words{ ":hamburger:","U+1F354",
      },
      Words{ ":hammer:","U+1F528",
      },
      Words{ ":hamster:","U+1F439",
      },
      Words{ ":hear_no_evil:","U+1F649",
      },
      Words{ ":heart:","U+2764",
      },
      Words{ ":heart_eyes_cat:","U+1F63B",
      },
      Words{ ":hearts:",
      },
      Words{ ":heavy_check_mark:","U+2714",
      },
      Words{ ":moyai:",":moai:","U+1F5FF",
      },
      Words{ ":izakaya_lantern:","U+1F3EE",
      },
      Words{ ":helicopter:","U+1F681",
      },
      Words{ ":hocho:","U+1F52A",
      },
      Words{ ":honeybee:","U+1F41D",
      },
      Words{ ":horse:","U+1F434",
      },
      Words{ ":horse_racing:","U+1F3C7",
      },
      Words{ ":hourglass:","U+231B",
      },
      Words{ ":house:","U+1F3E0",
      },
      Words{ ":female_detective:","U+1F575","U+1FE0F","U+200D","U+2640",
      },
      Words{ ":icecream:","U+1F366",
      },
      Words{ ":imp:","U+1F608",
      },
      Words{ ":it:","U+1F1EE","U+1F1F9",
      },
      Words{ ":jack_o_lantern:","U+1F383",
      },
      Words{ ":japanese_goblin:","U+1F47A",
      },
      Words{ ":jp:","U+1F1EF","U+1F1F5",
      },
      Words{ ":key:","U+1F511",
      },
      Words{ ":kiss:","U+1F48B",
      },
      Words{ ":kissing_cat:","U+1F63D",
      },
      Words{ ":koala:","U+1F428",
      },
      Words{ ":kr:","U+1F1F0","U+1F1F7",
      },
      Words{ ":lemon:","U+1F34B",
      },
      Words{ ":lipstick:","U+1F484",
      },
      Words{ ":lock:","U+1F512",
      },
      Words{ ":lollipop:","U+1F36D",
      },
      Words{ ":man:","U+1F468",
      },
      Words{ ":maple_leaf:","U+1F341",
      },
      Words{ ":mask:","U+1F637",
      },
      Words{ ":metal:","U+1F918",
      },
      Words{ ":microscope:","U+1F52C",
      },
      Words{ ":moneybag:","U+1F4B0",
      },
      Words{ ":monkey:","U+1F412",
      },
      Words{ ":mount_fuji:","U+1F5FB",
      },
      Words{ ":muscle:","U+1F4AA",
      },
      Words{ ":mushroom:","U+1F344",
      },
      Words{ ":musical_keyboard:","U+1F3B9",
      },
      Words{ ":musical_score:","U+1F3BC",
      },
      Words{ ":nail_care:","U+1F485",
      },
      Words{ ":new_moon:","U+1F311 ",
      },
      Words{ ":no_entry:","U+26D4",
      },
      Words{ ":nose:","U+1F443",
      },
      Words{ ":notes:",
      },
      Words{ ":nut_and_bolt:","U+1F529",
      },
      Words{ ":o:","U+2B55",
      },
      Words{ ":ocean:","U+1F30A",
      },
      Words{ ":ok_hand:","U+1F44C",
      },
      Words{ ":on:","U+1F51B",
      },
      Words{ ":package:","U+1F4E6",
      },
      Words{ ":palm_tree:","U+1F334",
      },
      Words{ ":panda_face:","U+1F43C",
      },
      Words{ ":paperclip:","U+1F4CE","U+1F587",
      },
      Words{ ":partly_sunny:","U+26C5","U+1F324","U+1F325",
      },
      Words{ ":passport_control:","U+1F6C2","U+1F6C3",
      },
      Words{ ":paw_prints:",
      },
      Words{ ":peach:",
      },
      Words{ ":penguin:",
      },
      Words{ ":phone:",
      },
      Words{ ":pig:",
      },
      Words{ ":pill:",
      },
      Words{ ":pineapple:",
      },
      Words{ ":pizza:",
      },
      Words{ ":point_left:",
      },
      Words{ ":point_right:",
      },
      Words{ ":poop:",
      },
      Words{ ":poultry_leg:",
      },
      Words{ ":pray:",
      },
      Words{ ":princess:",
      },
      Words{ ":purse:",
      },
      Words{ ":pushpin:",
      },
      Words{ ":rabbit:",
      },
      Words{ ":rainbow:",
      },
      Words{ ":raised_hand:",
      },
      Words{ ":recycle:",
      },
      Words{ ":red_car:",
      },
      Words{ ":registered:",
      },
      Words{ ":ribbon:",
      },
      Words{ ":rice:",
      },
      Words{ ":rocket:",
      },
      Words{ ":roller_coaster:",
      },
      Words{ ":rooster:",
      },
      Words{ ":ru:",
      },
      Words{ ":sailboat:",
      },
      Words{ ":santa:",
      },
      Words{ ":satellite:",
      },
      Words{ ":satisfied:",
      },
      Words{ ":saxophone:",
      },
      Words{ ":scissors:",
      },
      Words{ ":see_no_evil:",
      },
      Words{ ":sheep:",
      },
      Words{ ":shell:",
      },
      Words{ ":shoe:",
      },
      Words{ ":ski:",
      },
      Words{ ":skull:",
      },
      Words{ ":sleepy:",
      },
      Words{ ":smile:",
      },
      Words{ ":smiley_cat:",
      },
      Words{ ":smirk:",
      },
      Words{ ":smoking:",
      },
      Words{ ":snail:",
      },
      Words{ ":snake:",
      },
      Words{ ":snowflake:",
      },
      Words{ ":soccer:",
      },
      Words{ ":soon:",
      },
      Words{ ":space_invader:",
      },
      Words{ ":spades:",
      },
      Words{ ":speak_no_evil:",
      },
      Words{ ":star:",
      },
      Words{ ":stars:",
      },
      Words{ ":statue_of_liberty:",
      },
      Words{ ":steam_locomotive:",
      },
      Words{ ":sunflower:",
      },
      Words{ ":sunglasses:",
      },
      Words{ ":sunny:",
      },
      Words{ ":sunrise:",
      },
      Words{ ":surfer:",
      },
      Words{ ":swimmer:",
      },
      Words{ ":syringe:",
      },
      Words{ ":tada:",
      },
      Words{ ":tangerine:",
      },
      Words{ ":taxi:",
      },
      Words{ ":tennis:",
      },
      Words{ ":tent:",
      },
      Words{ ":thought_balloon:",
      },
      Words{ ":tm:",
      },
      Words{ ":toilet:",
      },
      Words{ ":tongue:",
      },
      Words{ ":tophat:",
      },
      Words{ ":tractor:",
      },
      Words{ ":trolleybus:",
      },
      Words{ ":nauseated_face:","U+1F922",
      },
      Words{ ":trophy:",
      },
      Words{ ":trumpet:",
      },
      Words{ ":turtle:",
      },
      Words{ ":two_men_holding_hands:",
      },
      Words{ ":two_women_holding_hands:",
      },
      Words{ ":uk:",
      },
      Words{ ":umbrella:",
      },
      Words{ ":unlock:",
      },
      Words{ ":us:",
      },
      Words{ ":v:",
      },
      Words{ ":vhs:",
      },
      Words{ ":violin:",
      },
      Words{ ":warning:",
      },
      Words{ ":watermelon:",
      },
      Words{ ":wave:",
      },
      Words{ ":wavy_dash:",
      },
      Words{ ":wc:",
      },
      Words{ ":wheelchair:",
      },
      Words{ ":woman:",
      },
      Words{ ":x:",
      },
      Words{ ":yum:",
      },
      Words{ ":zap:",
      },
      Words{ ":zzz:",
      },
	  },
  }
}
